#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftM,         tmotorTetrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightM,        tmotorTetrix, PIDControl, driveRight, encoder)
//added from Cosmos//
#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
//end of copyed code//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
wait = wait100Msec(1000);
waitJ = wait1000Msec(10000);
task main()
{
setMultipleMotors(64,leftM,rightM);
stopAllMotors();
wait;
setMultipleMotors(-64,leftM,rightM);
stopALLMotors();
wait;
motor[rightM]=64;
motor[leftM]=64;
stopAllMotors();
wait;
motor[leftM]=-64;
motor[rightM]=-64;
stopAllMotors();
wait;
setMultipleMotors(-64,leftM,rightM);
wait;
setMultipleMotors(64,leftM,rightM);
wait;
setMultipleMotors(-64,leftM,rightM);
wait;
setMultipleMotors(64,leftM,rightM);
stopALLMotors();
wait;
motor[rightM]=32;
motor[leftM]=64;
stopAllMotors();
wait;
motor[leftM]=32;
motor[rightM]=64;
stopAllMotors();
wait;
motor[leftM]=100;
motor[rightM]=-100;
wait;
setMultipleMotors(64,leftM,rightM);
wait;
setMultipleMotors(-64,leftM,rightM);
wait;
motor[rightM]=64;
motor[leftM]=64;
wait;
motor[leftM]=-64;
motor[rightM]=-64;
wait;
setMultipleMotors(-64,leftM,rightM);
wait;
setMultipleMotors(64,leftM,rightM);
wait;
setMultipleMotors(-64,leftM,rightM);
wait;
setMultipleMotors(64,leftM,rightM);
wait;
motor[rightM]=32;
motor[leftM]=64;
stopALLMotors;
wait;
getJoystickSettings(joystick);
motor[leftM]=joystick.joy1_y1;
motor[rightM]=joystick.joy2_y1;
waitJ;
stopALLMotors();
}
