#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftM,         tmotorTetrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightM,        tmotorTetrix, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
wait = wait100Msec(1000);
task main()
{
setMultipleMotors(64,leftM,rightM);
stopAllMotors();
wait;
setMultipleMotors(-64,leftM,rightm);
stopALLMotors();
wait;
motor[rightM]=64;
motor[leftM]=64;
stopAllMotors();
wait;
motor[leftM]=-64;
motor[rightM]=-64;
stopAllMotors();
wait;
setMultipleMotors(-64,leftM,rightm);
setMultipleMotors(64,leftM,rightm);
setMultipleMotors(-64,leftM,rightm);
setMultipleMotors(64,leftM,rightm);
stopALLMotors();
wait;
motor[rightM]=32;
motor[leftm]=64;
stopAllMotors();
wait;
motor[leftm]=32;
motor[rightM]=64;
stopAllMotors();
wait;
motor[leftM]=100;
motor[rightM]=-100;
wait;
setMultipleMotors(64,leftM,rightM);
wait;
setMultipleMotors(-64,leftM,rightm);
wait;
motor[rightM]=64;
motor[leftM]=64;
wait;
motor[leftM]=-64;
motor[rightM]=-64;
wait;
setMultipleMotors(-64,leftM,rightm);
wait;
setMultipleMotors(64,leftM,rightm);
wait;
setMultipleMotors(-64,leftM,rightm);
wait;
setMultipleMotors(64,leftM,rightm);
wait;
motor[rightM]=32;
motor[leftm]=64;
stopALLMotors;
}
