#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftM,         tmotorTetrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightM,        tmotorTetrix, PIDControl, driveRight, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     SL,            tmotorTetrix, openLoop) //up and down
#pragma config(Servo,  srvo_S3_C1_1,    SFR,                  tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    SFL,                  tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    SB,                   tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//blue is 45% +-5
//red is 67% +-5
//floor is 33% +-5
//atom ramp 1. move robot off ramp to other teams goals and move the big goal around and score in it (yours)
//2. score in big goal while being in the way of the other teams
//atom parking space  move other team's rolling goals(push them) , release a cascade, and score in high goal
bool team = false;
task main()
{
	setMultipleMotors(64,leftM,rightM);
	wait(10);
	stopAllMotors();
	setMultipleMotors(-64,leftM,rightM);
	wait(10);
	stopAllMotors(); 
servo[SFR]=0;
wait(1);
servoTarget[SFR]=30;
servo[SFR]=90;
getJoystickSettings(joystick);
wait(360);
setMultipleMotors(64,leftM,rightM);
	if (SensorValue[S1] >= 28 && SensorValue[S1] <=39 )
	{
		team = true;
		setMultipleMotors(64,leftM,rightM)
		wait(.2)
		
  }
  	else 
  		{
  			team = false;
 			}
 }
