#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     light1,         sensorLightInactive)
#pragma config(Sensor, S3,     light2,         sensorLightInactive)
#pragma config(Motor,  mtr_S1_C2_1,     scissorLiftRight, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     scissorLiftLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    frontGate,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    backGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(1 == 1)
	{
		getJoystickSettings(joystick);

		motor[frontleft] = joystick.joy1_y1;
		motor[frontright] = joystick.joy1_y2;

		if(joystick.joy1_TopHat == 0)
		{
			motor[frontleft] = 120; //forward
			motor[frontright] = 120;
	  }
		else if(joystick.joy1_TopHat == 4)
		{
			motor[frontleft] = -120; //forward
			motor[frontright] = -120;
		}
		else
		{
			motor[frontleft] = 0;
			motor[frontright] = 0;
		}

		if (joy2Btn(5) == 1)
		{
			motor[scissorLiftRight] = 120;
			motor[scissorLiftLeft] = 120;
		}
		else if (joy2Btn(7) == 1)
		{
			motor[scissorLiftLeft] = -120;
			motor[scissorLiftRight] = -120;
		}
		else
		{
			motor[scissorLiftRight] = 0;
			motor[scissorLiftLeft] = 0;
		}

		if (joy1Btn(8) == 1)
			{
				servo[frontGate] = 170;
				sleep(300);
				servo[frontGate] = 0;
			}

			if (joy1Btn(6) == 1)
			{
				if (servo[frontGate] == 155)
				{
					servo[frontGate] = 0;
				}
				else
				{
					servo[frontGate] = 155;
				}
			}

			if (joy2Btn(1) == 1)
			{
				servo[backGrab] = 35;
			}

			if (joy2Btn(2) == 1)
			{
				servo[backGrab] = 255;
			}

	}
}
